#!/bin/sh
#
# moloch-es 	Elasticsearch backend for moloch capture/viewer
#
# chkconfig:	2345 75 75
# description:	Elasticsearch backend for moloch capture/viewer

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
exec="/data/moloch/bin/run_es.sh"
prog="moloch-es"

LOCKFILE=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    daemon $exec
    echo -n $"Waiting for Elasticsearch..."
    sleep 15
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    return $RETVAL
}

stop() {
    echo -n $"Stopping Elasticsearch database gracefully..."
    curl -XPOST http://localhost:9200/_shutdown
    sleep 10
    echo -n $"Killing Elasticsearch process..."
    killproc java -TERM
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
	start
        ;;
    status)
        rh_status
        ;;
    *)
	echo "Usage: $prog {start|stop|status|restart}"
	exit 1
	;;
esac
exit $RETVAL

