#!/bin/sh
#
# moloch-view 	moloch viewer
#
# chkconfig:	2345 77 77
# description:	node.js server / moloch viewer webapp

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
exec="/data/moloch/bin/run_viewer.sh"
prog="moloch-view"

LOCKFILE=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    nohup $exec &
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog"
    killproc node-viewer -TERM
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
	start
        ;;
    status)
        rh_status
        ;;
    *)
	echo "Usage: $prog {start|stop|status|restart}"
	exit 1
	;;
esac
exit $RETVAL

